/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asdf;

/**
 *
 * @author Tungsten
 */
public class FieldsUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FieldsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crop1TF = new javax.swing.JTextField();
        clay1TF = new javax.swing.JTextField();
        wood1TF = new javax.swing.JTextField();
        iron1TF = new javax.swing.JTextField();
        ResultTF = new javax.swing.JTextField();
        CalculateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CropBonusTF = new javax.swing.JTextField();
        ClayBonusTF = new javax.swing.JTextField();
        WoodBonusTF = new javax.swing.JTextField();
        IronBonusTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CropResultTF = new javax.swing.JLabel();
        ClayResultTF = new javax.swing.JLabel();
        WoodResultTF = new javax.swing.JLabel();
        IronResultTF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crop1TF.setText("1");

        clay1TF.setText("1");

        wood1TF.setText("1");

        iron1TF.setText("1");

        ResultTF.setText("Result");

        CalculateButton.setText("Calculate");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Crop");

        jLabel2.setText("Clay");

        jLabel3.setText("Wood");

        jLabel4.setText("Iron");

        CropBonusTF.setText("0");

        ClayBonusTF.setText("0");
        ClayBonusTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClayBonusTFActionPerformed(evt);
            }
        });

        WoodBonusTF.setText("0");

        IronBonusTF.setText("0");

        jLabel5.setText("Bonus%");

        jLabel6.setText("Level");

        jLabel7.setText("Hours until gainz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(clay1TF)
                                    .addComponent(crop1TF)
                                    .addComponent(wood1TF, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CropBonusTF, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(ClayBonusTF)
                                    .addComponent(WoodBonusTF)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iron1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IronBonusTF, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 142, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CalculateButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ResultTF, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(ClayResultTF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WoodResultTF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IronResultTF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CropResultTF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crop1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(CropBonusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CropResultTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clay1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ClayBonusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClayResultTF, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wood1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(WoodBonusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(WoodResultTF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iron1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(IronBonusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IronResultTF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(ResultTF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(CalculateButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private static double ttgCrop(double level) { //ttg = time 'til gainz
        //kostnaður við upgrade
        double[] levelcost = {250, 415, 695, 1165, 1945, 3250, 5420, 9055, 15120, 25260, 42180, 70440, 117635, 196450, 328070, 547885};
        //production 
        double[] levelproduce = {5, 9, 15, 22, 33, 50, 70, 100, 145, 200, 280, 375, 495, 635, 800, 1000};
        //consumption
        double consumption = 1;
        if (level > 15) {
            consumption = 2;}
        else if (level < 6) {
            consumption = 0;}
       
        double ProductionGain = levelproduce[(int) level] - levelproduce[(int) level-1] - consumption;
        
        double ttg = levelcost[(int) level]/ProductionGain;
        return ttg;
    }
    private static double ttgWood(double level) { //ttg = time 'til gainz
        //kostnaður við upgrade
        double[] levelcost = {250, 415, 695, 1165, 1945, 3250, 5420, 9055, 15120, 25260, 42180, 70440, 117635, 196450, 328070, 547885};
        //production 
        double[] levelproduce = {5, 9, 15, 22, 33, 50, 70, 100, 145, 200, 280, 375, 495, 635, 800, 1000};
        //consumption
        double consumption = 2;
        if (level > 15) {
            consumption = 3;}
        else if (level < 6) {
            consumption = 1; }
        
        double ProductionGain = levelproduce[(int) level] - levelproduce[(int) level-1] - consumption;
        double ttg = levelcost[(int) level]/ProductionGain;
        return ttg;
    }       
    private static double ttgClay(double level) {
        //kostnaður við upgrade
        double[] levelcost = {250, 420, 700, 1170, 1940, 3250, 5425, 9060, 15125, 25250, 42185, 70440, 117635, 196450, 328075, 547875};
        //production 
        double[] levelproduce = {5, 9, 15, 22, 33, 50, 70, 100, 145, 200, 280, 375, 495, 635, 800, 1000};
        //consumption
        double consumption = 2;
        if (level > 15) {
            consumption = 3;
        }
        else if (level < 6) {
            consumption = 1; 
        }
        double ProductionGain = levelproduce[(int) level] - levelproduce[(int) level-1] - consumption;
        
        double ttg = levelcost[(int) level]/ProductionGain;
        return ttg;
    }
    private static double ttgIron(double level) {
        //kostnaður við upgrade
        double[] levelcost = {270, 450, 755, 1260, 2100, 3510, 5855, 9785, 16335, 27275, 45555, 76075, 127045, 212170, 354325, 591710};
        //production 
        double[] levelproduce = {5, 9, 15, 22, 33, 50, 70, 100, 145, 200, 280, 375, 495, 635, 800, 1000};
        //consumption
        double consumption = 2;
        if (level > 10) {
            consumption = 3;
        }        
        double ProductionGain = levelproduce[(int) level] - levelproduce[(int) level-1] - consumption;
        
        double ttg = levelcost[(int) level]/ProductionGain;
        return ttg;
    }
    
    //oasis ttg
    private static double Bonus(double perc, double prettg) { //tekur inn % og ttg
        double ttg = prettg/(1 + perc * 0.01);
        return ttg;
    }
    
    
    private static double minimum(double a, double b, double c, double d) {
        double min = a;
        if (min > b) {
            min = b;
        }
        if (min > c) {
            min = c;
        }
        if (min > d) {
            min = d;
        }
        return min;
    }
    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        double crop1, clay1, wood1, iron1, result, crop1ttg, clay1ttg, wood1ttg, iron1ttg;
        double CropBonus = 0, ClayBonus = 0, IronBonus = 0, WoodBonus = 0;
        crop1 = Integer.parseInt(crop1TF.getText()); 
        clay1 = Integer.parseInt(clay1TF.getText());
        wood1 = Integer.parseInt(wood1TF.getText());
        iron1 = Integer.parseInt(iron1TF.getText());
        try { 
            CropBonus = Double.parseDouble(CropBonusTF.getText()); } 
        catch (Exception e){};
        try {
            ClayBonus = Double.parseDouble(ClayBonusTF.getText());}
        catch (Exception e){};
        try {
            WoodBonus = Double.parseDouble(WoodBonusTF.getText());}
        catch (Exception e){};
        try {
            IronBonus = Double.parseDouble(IronBonusTF.getText());}
        catch (Exception e){};
        crop1ttg = Bonus(CropBonus, ttgCrop(crop1));
        clay1ttg = Bonus(ClayBonus, ttgClay(clay1));
        wood1ttg = Bonus(WoodBonus, ttgWood(wood1));
        iron1ttg = Bonus(IronBonus, ttgIron(iron1));
        CropResultTF.setText("" + (int) crop1ttg);
        ClayResultTF.setText("" + (int) clay1ttg);
        WoodResultTF.setText("" + (int) wood1ttg);
        IronResultTF.setText("" + (int) iron1ttg);
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void ClayBonusTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClayBonusTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClayBonusTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FieldsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FieldsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FieldsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FieldsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FieldsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JTextField ClayBonusTF;
    private javax.swing.JLabel ClayResultTF;
    private javax.swing.JTextField CropBonusTF;
    private javax.swing.JLabel CropResultTF;
    private javax.swing.JTextField IronBonusTF;
    private javax.swing.JLabel IronResultTF;
    private javax.swing.JTextField ResultTF;
    private javax.swing.JTextField WoodBonusTF;
    private javax.swing.JLabel WoodResultTF;
    private javax.swing.JTextField clay1TF;
    private javax.swing.JTextField crop1TF;
    private javax.swing.JTextField iron1TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField wood1TF;
    // End of variables declaration//GEN-END:variables
}
